class I18N:
    def __init__(self, language):
        if language == "EN":
            self.current_language_english()
        elif language == "TR":
            self.current_language_turkish()
        else:
            raise NotImplementedError("undefined languge")

    def current_language_english(self):
        self.username = "Username"
        self.password = "Password"
        self.fname = "First Name"
        self.lname = "Last Name"
        self.job_seeker = "Job Seeker"
        self.employer = "Employer"
        self.login = "Login"
        self.do_you_have_account = "Dont have an account yet?"
        self.invalid_u_p = "Invlaid username or password"
        self.ssn = "SSN*"
        self.dob_gender = "DOB/Gender*"
        self.phone_number = "Phone Number*"
        self.adress = "Adress"
        self.occupation = "Occupation"
        self.write_about_yourself = "Write about yourself"
        self.upload_picture = "Upload Profile Picture"
        self.upload_cv = "       Upload CV      "
        self.please_wait = "Please Wait"
        self.email = "Email"
        self.register = "Register"
        self.cancel = "Cancel"
        self.company_name= "Company Name"
        self.write_about_your_company = "Write about your company"
        self.please_fill_all_required_fields = "Please fill all required fields"
        self.username_taken = "This username is already taken. Please choose another one"
        self.category = "Category "
        self.company = "Company "
        self.location = "Location: "
        self.details = "Details: "
        self.job_adds = "Avalilable jobs"
        self.about_our_company = "About our company"
        self.job_desc = "Job description"
        self.required_q= "Required qualifications and skills"
        self.respons = "Responsibilities"
        self.no_of_view = "Number of views"
        self.no_aplicants = "Number of applicants"
        self.applicants = "APPLICANTS"
        self.apply = "Apply"
        self.succesfull_application = "Your application has been sent successfully!!"
        self.already_appilied = "Your application has already been received!"
        self.add_new_job = "Add new job advertisement"
        self.job_listing = "Job Listing for "
        self.about_me = "About me:"
        self.d_cv = "Download cv"
        self.go_back = "Go back"
        self.dob = "Date of birth"
        self.gender = "Gender"
        self.cv_disable = "CV is unavailable"
        self.job_title = "Job title: "
        self.publish = "Publish"
        self.job_published = "job advertisement published successfully!!"


    def current_language_turkish(self):
        self.username = "Kullanıcı adı"
        self.password = "Şifre"
        self.fname = "İsim"
        self.lname = "Soy İsim"
        self.employer = "Aday"
        self.job_seeker = "İş veren"
        self.login = "Oturum aç"
        self.do_you_have_account = "Hâlâ hesabın yok mu?"
        self.invalid_u_p = "Geçersiz kullanıcı adı yada şifre"
        self.ssn = "T.C. kimlik no"
        self.dob_gender = "Doğ. tarihi/Cins."
        self.phone_number = "Telefon "
        self.adress = "Adres"
        self.occupation = "Meslek"
        self.write_about_yourself = "Kendiniz hakkında yazın"
        self.upload_picture = "Profil fotoğrafı yükle"
        self.upload_cv = "    Özgeçmiş yükle    "
        self.please_wait = "Lütfen bekleyin"
        self.email = "E-posta"
        self.register = "Kayıt ol"
        self.cancel = "İptal"
        self.company_name = "Şirket ismi"
        self.write_about_your_company = "Şirketiniz hakkında yazın"
        self.please_fill_all_required_fields = "Lütfen tüm gerekli alanları doldurun"
        self.username_taken = "Bu kullanıcı adı zaten alınmış. Lütfen başka birini seçiniz"
        self.category = "Kategori: "
        self.company = "Şirket: "
        self.location = "Konum: "
        self.details = "Detaylar: "
        self.job_adds = "İş ilanları"
        self.about_our_company = "Şirketimiz hakkında"
        self.job_desc = "İş tanımı"
        self.required_q = "Gerekli Beceriler"
        self.respons = "Sorumluluklar"
        self.no_of_view = "Görüntülenme Sayısı"
        self.no_aplicants = "Başvurular"
        self.applicants = "Adaylar "
        self.apply = "Başvur"
        self.succesfull_application = "Başvurunuz başarıyla gönderildi!"
        self.already_appilied = "Başvurunuz zaten alındı!"
        self.add_new_job = "Yeni iş ilanı ekle"
        self.job_listing = "Şirketin iş ilanları: "
        self.about_me = "Hakkımda: "
        self.d_cv = "Özgeçmiş indir: "
        self.go_back = "Geri Dön"
        self.dob = "Doğum tarihi: "
        self.gender = "Cinsiyet: "
        self.cv_disable = "CV mevcut değil"
        self.job_title = "İlan başlığı"
        self.publish = "Yayınla"
        self.job_published = "iş ilanı başarıyla yayınlandı!"